package org.dhamma.bell.scheduler

import android.app.AlarmManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import org.dhamma.bell.MainActivity
import org.dhamma.bell.data.AppDatabase
import org.dhamma.bell.data.CourseTemplate
import org.dhamma.bell.data.EventType
import org.dhamma.bell.data.ScheduledBellEntity
import java.time.LocalDate
import java.time.ZoneId
import java.util.UUID

/**
 * Turns a CourseTemplate + a chosen Start Date into concrete Room rows,
 * then arms each future one as an exact AlarmManager.setAlarmClock() alarm
 * so it survives Doze and screen-off battery optimization.
 */
class AlarmScheduler(private val context: Context) {

    private val alarmManager: AlarmManager =
        context.getSystemService(Context.ALARM_SERVICE) as AlarmManager

    private val db: AppDatabase by lazy { AppDatabase.getInstance(context) }
    private val zoneId: ZoneId = ZoneId.systemDefault()

    /** True if this device requires the user to grant "Alarms & reminders" (Android 12+). */
    fun canScheduleExactAlarms(): Boolean {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            alarmManager.canScheduleExactAlarms()
        } else {
            true
        }
    }

    /**
     * Computes every event's real datetime from [template] + [startDate], persists them,
     * cancels any currently active course, and arms alarms for every future event.
     */
    suspend fun scheduleCourse(template: CourseTemplate, startDate: LocalDate) {
        // Cancel whatever course is currently active - only one active course at a time.
        cancelActiveCourse()

        val courseInstanceId = UUID.randomUUID().toString()
        val entities = template.events.map { event ->
            val eventDate = startDate.plusDays(event.dayOffset.toLong())
            val eventDateTime = eventDate.atTime(event.time)
            val triggerAtMillis = eventDateTime.atZone(zoneId).toInstant().toEpochMilli()

            ScheduledBellEntity(
                courseInstanceId = courseInstanceId,
                courseTemplateId = template.id,
                courseDisplayName = template.displayName,
                dayOffset = event.dayOffset,
                eventLabel = event.label,
                eventType = event.type,
                audioFileName = event.audioFileName,
                triggerAtMillis = triggerAtMillis
            )
        }

        db.bellDao().insertAll(entities)

        // Re-read back so we have real autogenerated IDs to use as PendingIntent request codes.
        val now = System.currentTimeMillis()
        val toArm = db.bellDao().getUntriggeredBells().filter { it.triggerAtMillis > now }
        toArm.forEach { armAlarm(it) }

        Log.i(TAG, "Scheduled ${entities.size} events for '${template.displayName}', armed ${toArm.size} future alarms.")
    }

    /** Cancels the currently active course's DB rows and any live AlarmManager entries. */
    suspend fun cancelActiveCourse() {
        val activeCourseId = db.bellDao().getActiveCourseInstanceId() ?: return
        val untriggered = db.bellDao().getUntriggeredBells()
            .filter { it.courseInstanceId == activeCourseId }
        untriggered.forEach { disarmAlarm(it) }
        db.bellDao().cancelCourse(activeCourseId)
        Log.i(TAG, "Cancelled active course $activeCourseId (${untriggered.size} pending alarms disarmed).")
    }

    /** Called by BootReceiver: re-arms every untriggered future alarm from Room after a reboot. */
    suspend fun rearmAllFromDatabase() {
        val now = System.currentTimeMillis()
        val toArm = db.bellDao().getUntriggeredBells().filter { it.triggerAtMillis > now }
        toArm.forEach { armAlarm(it) }
        Log.i(TAG, "Boot recovery: re-armed ${toArm.size} alarms from Room.")
    }

    fun armAlarm(bell: ScheduledBellEntity) {
        val pendingIntent = buildPendingIntent(bell.id)
        val showIntent = PendingIntent.getActivity(
            context,
            bell.id.toInt(),
            Intent(context, MainActivity::class.java),
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )

        // setAlarmClock() gets the same Doze-bypassing treatment as a user-visible alarm clock,
        // which is the most reliable exact-timing API available on an unattended TV box.
        val info = AlarmManager.AlarmClockInfo(bell.triggerAtMillis, showIntent)
        alarmManager.setAlarmClock(info, pendingIntent)
    }

    fun disarmAlarm(bell: ScheduledBellEntity) {
        val pendingIntent = buildPendingIntent(bell.id)
        alarmManager.cancel(pendingIntent)
    }

    private fun buildPendingIntent(bellId: Long): PendingIntent {
        val intent = Intent(context, BellAlarmReceiver::class.java).apply {
            action = ACTION_TRIGGER_BELL
            putExtra(EXTRA_BELL_ID, bellId)
        }
        return PendingIntent.getBroadcast(
            context,
            bellId.toInt(),
            intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )
    }

    companion object {
        const val TAG = "AlarmScheduler"
        const val ACTION_TRIGGER_BELL = "org.dhamma.bell.action.TRIGGER_BELL"
        const val EXTRA_BELL_ID = "extra_bell_id"
    }
}

/** Convenience so callers don't need to import EventType separately. */
fun ScheduledBellEntity.isSilentBlock(): Boolean =
    eventType == EventType.SILENT_BLOCK_START || eventType == EventType.SILENT_BLOCK_END
